#!/bin/bash
#
#  Copyright 2016 Matteo Alessio Carrara <sw.matteoac@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

set -e -u

if [[ $# -lt 3 ]]
then
	echo Uso: ftp_user ftp_pass ftp_hostname versione
	exit 1
fi


FTP_USER=$1
FTP_PASS=$2
FTP_HOSTNAME=$3
VERSION=$4

REPO_PATH=$(git rev-parse --show-toplevel)
REPO_NAME=$(basename $REPO_PATH)
TARBALL_FILENAME=$REPO_NAME-$VERSION.tar.xz
FTP_DIR=public_html

git tag -m "Nuova versione" $VERSION master
git push --follow-tags origin master

git checkout release

git apply-branch master
git add .
git commit -m "Sincronizzazione con master"

repo-lint $REPO_PATH
git add .
git commit -m "Ripulito repo"

git push origin release

git archive --format=tar release | xz -6 > $TARBALL_FILENAME
ncftpput -v -u $FTP_USER -p $FTP_PASS $FTP_HOSTNAME $FTP_DIR $TARBALL_FILENAME
rm ./$TARBALL_FILENAME

git checkout master

echo
echo Github: $(sed "s/.git$//g" <<< $(git remote get-url origin))/tree/release
echo Download: $FTP_HOSTNAME/$TARBALL_FILENAME