#!/bin/bash
#
#  Copyright 2016 Matteo Alessio Carrara <sw.matteoac@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

set -e -u

if [[ $# -lt 1 ]]
then
	echo Specificare il numero di versione
	exit 1
fi


git checkout -B release

git apply-branch master
git add .
git commit -m "Sincronizzazione con master"

repo-lint $(git rev-parse --show-toplevel)
git add .
git commit -m "Ripulito repo"

git tag -m "Nuova versione" $1

git checkout master